### ISSUE TITLE
Full report-gen automation variable location 

### ISSUE THREAD

**Issue by gbooks** [innoventsolutions/pentaho-lambda-report-gen#2]
Priority: 1

In its current form the pentaho-lambda-report-gen for Lambda-Pentaho Integration works well as a semi-automated or one-off reporting solution.

For full automation using AWS CloudWatch, some changes to how and where variables are managed will need to take place.  Currently, the following variables are submitted via API Gateway query string:
```
report (prpt_file)
outputType (output_type)
folder (output_s3_bucket)
file (output_file)
custom params
```
And the following are set as Lamba function environment variables:
```
folder (output_s3_bucket)
OutputType (output_type)
s3_bucket (prpt_s3_bucket)
```
Allowing all variables to be set as Lambda environment variables will make it that a Lamba function with the Pentaho-lambda-report-gen JAR file can be automated with AWS CloudWatch.

Thanks.
GBooks

**Comment by SteveSchafer-Innovent** [comment]
This was committed by Jaret on Jan 9.
