### ISSUE TITLE
Nice to have: Variables in any location

### ISSUE THREAD

**Issue by gbooks** [innoventsolutions/pentaho-lambda-report-gen#3]
Priority: 3 (or lower!)

As mentioned in a previous issue request, some variables are passed in the query string and some are set as environment variables.

It would be nice if all variables could be passed/set from any of the following:
- Lambda environment variables
- passed in the API Gateway query string
- sent as a JSON object in the API Gateway body

If the same variable existed in multiple locations, JSON would trump query string would trump Environment variables.

Thanks.
GBooks

**Comment by pipebaum** [comment]
Thanks, we will have a look at this in a later release. Going to take care of the Priority 1 issues first.

**Comment by SteveSchafer-Innovent** [comment]
I introduced code to accept raw JSON in the request body.  The JSON looks like this:
{
    "prpt_file": "test",
    "output_type": "pdf",
    "output_s3_bucket": "sstest0323",
    "output_file": "test-pentaho",
    "prpt_s3_bucket": "sstest0323"
}
This works with Lambda Proxy integration.  JSON trumps query string trumps environment variables on a per-variable basis.

**Comment by gbooks** [comment]
Thanks Steve

It looks like you addressed a couple of remaining requests I had.  Are your changes included in the current /versions/pentahosyncreporting-1.0.0.jar?  That file does not appear to have been updated.  It looks like the .java files in /pentaho-report-generator/src were recently updated.  I've been using the original .jar file in my Lambda functions.

I am planning to start implementing the changes you recently made in the next couple weeks, so advice on how to use your version, or where I can download the latest .jar would be appreciated.

Also, as for versioning, the original .jar file was updated a number of times when it was built by jward-innovent but the file name remained the same.  When I downloaded each new version, I did versioning on my end.  I am calling the previous version pentahosyncreporting-1.0.0.6.jar and will plan to call your version pentahosyncreporting-1.0.0.7.jar unless you add it here as pentahosyncreporting-1.1.0.jar or something similar.

Please advise.

Thanks again.
GBooks
